// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gibbs_lm
List gibbs_lm(NumericVector y, NumericMatrix x, int steps);
RcppExport SEXP _iNZightBayes_gibbs_lm(SEXP ySEXP, SEXP xSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type steps(stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_lm(y, x, steps));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_one_numeric
List gibbs_one_numeric(NumericVector y, int steps, int burnin, int thin, double mu_0, double sigma2_0, double alpha, double beta);
RcppExport SEXP _iNZightBayes_gibbs_one_numeric(SEXP ySEXP, SEXP stepsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP mu_0SEXP, SEXP sigma2_0SEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type mu_0(mu_0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_0(sigma2_0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_one_numeric(y, steps, burnin, thin, mu_0, sigma2_0, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iNZightBayes_gibbs_lm", (DL_FUNC) &_iNZightBayes_gibbs_lm, 3},
    {"_iNZightBayes_gibbs_one_numeric", (DL_FUNC) &_iNZightBayes_gibbs_one_numeric, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_iNZightBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
