# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs sampler for single numeric mean and variance
#'
#' Description and details
#'
#' @param y vector of values
#' @param steps number of steps
gibbs_one_numeric_cpp <- function(y, steps, burnin, thin = 1L, mu_0 = 0.0, sigma2_0 = 1e6, alpha = 1e-3, beta = 1e-3) {
    .Call('_iNZightBayes_gibbs_one_numeric_cpp', PACKAGE = 'iNZightBayes', y, steps, burnin, thin, mu_0, sigma2_0, alpha, beta)
}

rcpp_hello_world <- function() {
    .Call('_iNZightBayes_rcpp_hello_world', PACKAGE = 'iNZightBayes')
}

