# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs Sample for Single Mean and Variance
#'
#' Gibbs sampler to sample mean and variance of one numeric variable
#'
#' @details
#' Assumes conjugate Normal-Inverse-Gamma priors on mean and variance:
#' \deqn{y \sim \mathrm{Normal}(\mu, \sigma^2)}
#'
#' @param y a vector of values
#' @param steps number of iterations to run Gibbs sampler for
#' @param burnin number of burn-in iterations to discard before proper steps
#' @param thin thinning factor (default 1)
#' @param mu_0 prior mean for mu (default 0)
#' @param sigma2_0 prior variance for mu (default 1e6)
#' @param alpha prior shape parameter for sigma2 (default 1e-3)
#' @param beta prior scale parameter for sigma2 (default 1e-3)
gibbs_one_numeric_cpp <- function(y, steps, burnin, thin = 1L, mu_0 = 0.0, sigma2_0 = 1e6, alpha = 1e-3, beta = 1e-3) {
    .Call('_iNZightBayes_gibbs_one_numeric_cpp', PACKAGE = 'iNZightBayes', y, steps, burnin, thin, mu_0, sigma2_0, alpha, beta)
}

rcpp_hello_world <- function() {
    .Call('_iNZightBayes_rcpp_hello_world', PACKAGE = 'iNZightBayes')
}

